Repository G1antPandaBear/recom-server-v1, pull requests merged in 2022-07, with the labels that each got.

#5 🚀 :: (#4) Repository 테스트
  .gitignore
  build.gradle
  src/main/java/com/pandabear/recom/domain/document/entity/Document.java
  src/main/java/com/pandabear/recom/domain/document/repository/DocumentRepository.java
  src/main/java/com/pandabear/recom/global/redis/config/RedisConfig.java
  src/main/java/com/pandabear/recom/global/redis/entity/DocAccessCode.java
  src/main/java/com/pandabear/recom/global/redis/repository/DocAccessCodeRepository.java
  src/main/resources/application.properties
  src/test/java/com/pandabear/recom/jpa/DocumentRepoTest.java
  src/test/java/com/pandabear/recom/redis/DocAccessCodeRepoTest.java
  src/test/java/resources/application-test.properties
Labels: hotfix, feat, test

#13 :rocket: :: (#12) AccessCodeService 리펙토링 및 테스트
  src/main/java/com/pandabear/recom/domain/document/ro/DocumentIdRO.java
  src/main/java/com/pandabear/recom/global/redis/entity/DocAccessCode.java
  src/main/java/com/pandabear/recom/global/redis/service/AccessCodeService.java
  src/main/java/com/pandabear/recom/global/util/RecordFileUtil.java
  src/test/java/com/pandabear/recom/jpa/DocumentRepoTest.java
  src/test/java/com/pandabear/recom/redis/DocAccessCodeRepoTest.java
  src/test/java/com/pandabear/recom/service/accesscode/AccessCodeServiceTest.java
  src/test/java/com/pandabear/recom/util/MultiPartFileTest.java
  src/test/java/com/pandabear/recom/util/TestUtil.java
Labels: refactor, test

#14 :rocket: :: (#7) DocumentService 구현
  src/main/java/com/pandabear/recom/domain/document/entity/Document.java
  src/main/java/com/pandabear/recom/domain/document/ro/DocumentRo.java
  src/main/java/com/pandabear/recom/domain/document/service/DocumentService.java
Labels: feat

#23 :rocket: :: (#22) address, title, createdAt 추가
  src/main/java/com/pandabear/recom/domain/document/controller/DocumentController.java
  src/main/java/com/pandabear/recom/domain/document/dto/ContentDto.java
  src/main/java/com/pandabear/recom/domain/document/entity/Document.java
  src/main/java/com/pandabear/recom/domain/document/ro/ContentRO.java
  src/main/java/com/pandabear/recom/domain/document/service/DocumentService.java
Labels: feat

#24 🚀 :: (#16) export files
  build.gradle
  src/main/java/com/pandabear/recom/domain/document/controller/DocumentController.java
  src/main/java/com/pandabear/recom/domain/document/service/DocumentService.java
  src/main/java/com/pandabear/recom/domain/document/type/ExportType.java
  src/main/java/com/pandabear/recom/global/config/AppProperties.java
  src/main/java/com/pandabear/recom/global/config/ExportTypeConverter.java
  src/main/java/com/pandabear/recom/global/config/WebMvcConfiguration.java
  src/main/java/com/pandabear/recom/global/util/DocxFileUtil.java
  src/main/java/com/pandabear/recom/global/util/FileUtil.java
  src/main/java/com/pandabear/recom/global/util/HwpFileUtil.java
  src/main/java/com/pandabear/recom/global/util/MdFileUtil.java
Labels: feat

#25 :rocket: :: (#21) CSS, HTML
  src/main/java/com/pandabear/recom/domain/document/controller/DocumentController.java
  src/main/java/com/pandabear/recom/domain/document/dto/ContentDto.java
  src/main/java/com/pandabear/recom/domain/document/entity/Document.java
  src/main/java/com/pandabear/recom/domain/document/service/DocumentService.java
  src/main/resources/static/img/docx.png
  src/main/resources/static/img/hwp.png
  src/main/resources/static/img/md.png
  src/main/resources/templates/document.html
  src/main/resources/templates/update.html
Labels: feat

#27 :rocket: :: (#26) update html;
  src/main/java/com/pandabear/recom/domain/document/controller/DocumentController.java
  src/main/resources/templates/document.html
  src/main/resources/templates/update.html
Labels: refactor, feat
